### Goal Description

The Economies goal captures the economic value associated with marine industries using revenue from marine sectors. It is composed of a single component, revenue. <!--- Due to a lack data from specific sectors, **for the BHI, this goal is measured by per capita GDP of each region, relative to the national per capita GDP.** --->

### Model & Data

Data for each country were downloaded from the [“EU-Study on Blue Growth, Maritime Policy and the EU Strategy for the Baltic Sea Region”](https://webgate.ec.europa.eu/maritimeforum/node/3550), which provided 2010 sector-specific revenue data, or Gross Value Added (GVA), in the country-specific Appendix. The report also identified the potential for Blue Growth in each of the EU Member States (MS) of the Baltic Sea Region (BSR) as well as at sea-basin level. 

The goal model compares the combined total revenue per country and the reference revenue of that country. Each country receives the same score because the reference point (see below) is a fixed percentage growth of that country's revenue in 2010. Country-level data is then distributed to BHI regions. (Due to a lack of data, Russian regions (19, 22, 33) have NA scores.)


### Reference points

As reference points we used a 1.5% annual growth between 2010 and 2020, as envisioned in the blue growth report. 

### Considerations for *BHI 2.0*

<!---
In this assessment, GDP used is for entire NUTS3, but divided among populations along a 25km buffer along the shore. 

Population data was not extracted for the entire NUTS3 area, only for the buffer area.  Therefore, the entire GDP for the NUTS3 is allocated among BHI regions, rather than only the GDP associated with the population in the buffer.
--->

### Other information

*external advisors/goalkeepers: Martin Quaas and Wilfried Rickels.*
