### Goal Description

Tourism in coastal areas is a major component of thriving coastal communities and a measure of how much people value ocean systems, i.e. by traveling to coastal and ocean areas. This goal is not about the revenue or livelihoods that are generated by tourism and recreation (that is captured in the livelihoods goal) but instead captures the value that people have for experiencing and enjoying coastal areas. A score of 100 means a region utilizes its full recreational potential without harming the ecosystem. 

In the BHI, we used employment data from the EU Study on Blue Growth (see below) to assess the status of Tourism. Three sectors were included: Coastal tourism, Yachting and maris, and Cruise tourism. No sustainability measure of any of the blue sectors exist yet on the Baltic Sea scale, and thus was not included in this study. 

### Model & Data

Data for each country were downloaded from the [EU-Study on Blue Growth](https://webgate.ec.europa.eu/maritimeforum/node/3550), Maritime Policy and the EU Strategy for the Baltic Sea Region” identified the potential for Blue Growth in each of the EU Member States (MS) of the Baltic Sea Region (BSR) and at sea basin level.

<!---
The tourism model incorporates the nights of stay in accommodations and compare that to the reference point. 

We used Eurostat dataset on [nights spent at tourist accommodation establishments](http://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=tour_occ_nin2&lang=en) by all NUTS regions. [tour_occ_nin2] 
--->

### Reference points

Study in support of policy measures for maritime and coastal tourism at EU level (Page 157) states that the Nordic Countries sea basins tourism has a potential to grow annually by 2.2 % until 2020. We therefore set the reference point to an annual growth of 2.2% for ten years from 2010 onwards for all three tourism categories (see above).


### Considerations for *BHI 2.0*

<!---MISSING data for region 19, 22, 30, 33 --->

### Other information
